name: rtm
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - gdal
  - ipython
  - jupyterlab
  - numpy<1.22  # TEMPORARY
  - obspy
  - pip
  - utm
  - xarray
  - pip:
    - git+https://github.com/uafgeotools/waveform_collection.git@fix-bulk
    - --editable .
